# SERVIDOR
server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: poc
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/multi_tenant
    username: postgres
    password: 415782
  h2:
    console:
      enabled: true
      path: /h2
